version: '3'

services:
  sales_db:
    build:
      dockerfile: ./db_docker/Dockerfile
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - sales_network

  sales_api:
    build:
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    ports:
      - 8000:8000
    networks:
      - sales_network
    depends_on:
      - sales_db

networks:
  sales_network:
    driver: bridge
